development:
  adapter: postgresql
  encoding: unicode
  database: dwolrd_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dwolrd_test
  pool: 5
  username: 
  password:

production:
  encoding: utf8
  pool: 15